In [1]:
import torch
import pandas as py
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


INTRODUCTION TO TENSORS

Creating Tensors

In [2]:
scalar = torch.tensor(7)
print(scalar)
scalar.ndim
#get scalar back as python int
scalar.item()

tensor(7)


7

In [3]:
#vector
vector = torch.tensor([7,7])
print(vector)
vector.ndim
vector.shape

tensor([7, 7])


torch.Size([2])

In [4]:
#MATRIX
matrix = torch.tensor(([[7,8],[9,10]]))
print(matrix)
matrix.ndim
matrix.shape

tensor([[ 7,  8],
        [ 9, 10]])


torch.Size([2, 2])

In [5]:
#tensor
tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
print(tensor)
tensor.ndim
print(tensor.shape)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
torch.Size([1, 3, 3])


In [6]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [7]:
random_tensor = torch.rand(3,4,1)
print(random_tensor)
random_tensor.ndim

tensor([[[0.7514],
         [0.5699],
         [0.6764],
         [0.5627]],

        [[0.2858],
         [0.5391],
         [0.4091],
         [0.6914]],

        [[0.2789],
         [0.2709],
         [0.2647],
         [0.3457]]])


3

In [8]:
#creating tensor with similar shape to an image tensor
random_image_size = torch.rand(size=(224, 224, 3))# height, width, color channels
print(random_image_size.shape)
random_image_size.ndim

torch.Size([224, 224, 3])


3

Creating a Range of tensors and tensors-like

In [9]:
#use  torch.range() to get deprecated message, use torch.arrange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
#creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatypes

In [11]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = torch.float16,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [12]:
#converting Float32 to float 16
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

Tensor Operation(+,-,*,/)
Matrix Multiplication  

In [13]:
tensor_1 = torch.tensor([1,2,3])
tensor_1+10

tensor([11, 12, 13])

In [14]:
tensor_1*11

tensor([11, 22, 33])

In [15]:
tensor_1-10

tensor([-9, -8, -7])

In [16]:
torch.mul(tensor_1,10)

tensor([10, 20, 30])

In [17]:
#diff between pytorch and normal multiplication
%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

CPU times: user 3 µs, sys: 1e+03 ns, total: 4 µs
Wall time: 9.06 µs
tensor([[ 1,  4,  9],
        [ 9, 36, 81],
        [ 4, 16, 25]])


In [19]:
start = torch.cuda.Event(enable_timing=True)
end = torch.cuda.Event(enable_timing=True)

start.record()
mul = torch.matmul(tensor,tensor)
print(mul.cpu)
end.record()
# Waits for everything to finish running
torch.cuda.synchronize()

print(start.elapsed_time(end))

RuntimeError: ignored

In [20]:
   #common Errors : Shape Errors while matrix multiplication
   #SHapes for matrix multiplication
   tensor_A = torch.tensor(([1,2],
                            [3,4],
                            [5,6]))
   tensor_B = torch.tensor(([7,8],
                            [8,9],
                            [9,10]))
   torch.mm(tensor_A, tensor_B)

RuntimeError: ignored

In [21]:
#To Fix our tensor shape Issues we can manipulate using transpose
tensor_B.T

tensor([[ 7,  8,  9],
        [ 8,  9, 10]])

In [22]:
output = torch.mm(tensor_A,tensor_B.T)
output

tensor([[ 23,  26,  29],
        [ 53,  60,  67],
        [ 83,  94, 105]])

In [23]:
#Tensor Aggregation

In [24]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [25]:
#min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [26]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [27]:
torch.mean(x)
'''---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-12-455868396db1> in <cell line: 1>()
----> 1 torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long
'''


RuntimeError: ignored

In [28]:
#torch.mean requires a tensor of float 32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [29]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [30]:
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [33]:
#Reshaping - Reshapes an input tensor to a defined shape
y=torch.arange(1.,10.)
y, y.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [35]:
y_rehape = y.reshape(1,9)
y_rehape, y_rehape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [39]:
z_reshape = y_rehape.reshape(9,1)
z_reshape, z_reshape.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [47]:
w_reshaped = y_rehape.reshape(3,3)
w_reshaped, w_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))